layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name
      - Algos
      - swapnilkishore.github.io
      - hello-world
      - SimpleMessenger

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: iamswapnilkishore
  # keybase: your_username
  linkedin: iamswapnilkishore
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: React
    web_url: https://reactjs.org/
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/react/react.png

  - name: Android
    web_url: https://www.android.com/
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/android/android.png

  - name: Distributed Systems
    web_url: https://amturing.acm.org/award_winners/lamport_1205376.cfm
    image_url: http://nanocheeze.com/ncz/images/distributed.png

  - name: AWS 
    web_url: https://aws.amazon.com/what-is-aws/
    image_url: https://blog.scottlogic.com/dsmith/assets/featured/aws-logo.png

  - name: Reactor/Reactive Streams
    web_url: https://projectreactor.io/
    image_url: https://avatars1.githubusercontent.com/u/4201559?s=400&v=4

theme: jekyll-theme-tactile
